ftp:
  image: mcreations/ftp
  ports:
    - "11021:21"
    - "65000-65004:65000-65004"
  volumes:
    - "/tmp/ftp:/data/webservice"
  environment:
    FTP_USER: "webservice"
    FTP_PASS: "rif+pan"
    HOST: "localhost"
    PASV_MIN_PORT: "65000"
    PASV_MAX_PORT: "65004"
